version: "3.7"
services:

  app:
    image: lynam/go-oauth
    container_name: go-oauth
    restart: on-failure
    ports:
    - 5001:5001
#    build:
#      context: ../
#      dockerfile: ./docker/Dockerfile
#      args:
#        GITHUB_TOKEN: "d7519779515245e32e346444a458377f501b70b0"
    links:
      - redis-service
      - mysql-service
      - nat-service
    env_file:
      - ../.env
    environment:
      DB_HOST: mysql-service
      DB_PORT: 3306
      DB_NAME: blog
      DB_USER:  admin
      DB_PASSWORD: admin
      REDIS_URL: redis-service:6379
      NAT_URL: nat-service
      APP_PORT: 5001
    networks:
      - backend
    depends_on:
      - redis-service
      - mysql-service
      - nat-service

  redis-service:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - backend

  mysql-service:
    image: mysql:8.0.18
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: blog
    restart: always
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - backend

  nat-service:
    image: nats:latest
    container_name: nats
    ports:
    - 4222:4222
    expose:
      - 4222
    networks:
      - backend

networks:
  backend:
