version: "3.7"

services:
  go-oauth:
    image: lynam/go-oauth
    container_name: go-oauth
    restart: on-failure
    ports:
      - 5001:5001
    links:
      - redis-service
      - mysql-service
      - nat-service
    env_file:
      - ../.env
    environment:
      DB_HOST: mysql-service
      DB_PORT: 3306
      DB_NAME: blog
      DB_USER:  admin
      DB_PASSWORD: admin
      REDIS_URL: redis-service:6379
      NAT_URL: nat-service
      APP_PORT: 5001
    networks:
      - backend
    depends_on:
      - redis-service
      - mysql-service
      - nat-service

  go-user:
    image: lynam/go-user
    container_name: go-user
    restart: on-failure
    ports:
      - 5002:5002
    links:
      - redis-service
      - mysql-service
      - nat-service
    env_file:
      - ../.env
    environment:
      DB_HOST: mysql-service
      DB_PORT: 3306
      DB_NAME: blog
      DB_USER:  admin
      DB_PASSWORD: admin
      REDIS_URL: redis-service:6379
      NAT_URL: nat-service
      APP_PORT: 5001
    networks:
      - backend
    depends_on:
      - redis-service
      - mysql-service
      - nat-service