version: "3.7"

services:
  redis-service:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - backend

  mysql-service:
    image: mysql:8.0.18
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: blog
    restart: always
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - backend

  nat-service:
    image: nats:latest
    container_name: nats
    ports:
    - 4222:4222
    expose:
      - 4222
    networks:
      - backend

networks:
  backend:
